language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0
env:
  global:
    - SPRING_DEBUG=1
  matrix:
    - RAILS_VERSION="~> 4.2.0"
before_script:
  - "[ $TRAVIS_RUBY_VERSION = \"1.9.3\" ] && travis_retry gem install mime-types --version \"~> 2\" || true"
  - travis_retry gem install rails --version "$RAILS_VERSION"
